package io.github.drumber.kitsune.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import io.github.drumber.kitsune.constants.AppTheme

// ── DEFAULT (Kitsune Red) ─────────────────────────────────────────────────────

internal val DefaultLightColorScheme = lightColorScheme(
    primary = Color(0xFF904B3F),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDAD4),
    onPrimaryContainer = Color(0xFF3A0A04),
    inversePrimary = Color(0xFFFFB4A7),
    secondary = Color(0xFF775651),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDAD4),
    onSecondaryContainer = Color(0xFF2C1511),
    tertiary = Color(0xFF6F5C2E),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFAE0A6),
    onTertiaryContainer = Color(0xFF251A00),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFF8F6),
    onBackground = Color(0xFF231918),
    surface = Color(0xFFFFF8F6),
    onSurface = Color(0xFF231918),
    surfaceVariant = Color(0xFFF5DDD9),
    onSurfaceVariant = Color(0xFF534340),
    inverseSurface = Color(0xFF392E2C),
    inverseOnSurface = Color(0xFFFFEDEA),
    outline = Color(0xFF857370),
    outlineVariant = Color(0xFFD8C2BE),
    scrim = Color(0xFF000000),
    surfaceDim = Color(0xFFE8D6D3),
    surfaceBright = Color(0xFFFFF8F6),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFF0EE),
    surfaceContainer = Color(0xFFFCEAE7),
    surfaceContainerHigh = Color(0xFFF7E4E1),
    surfaceContainerHighest = Color(0xFFF1DFDB),
)

internal val DefaultDarkColorScheme = darkColorScheme(
    primary = Color(0xFFFFB4A7),
    onPrimary = Color(0xFF561E15),
    primaryContainer = Color(0xFF733429),
    onPrimaryContainer = Color(0xFFFFDAD4),
    inversePrimary = Color(0xFF904B3F),
    secondary = Color(0xFFE7BDB5),
    onSecondary = Color(0xFF442A25),
    secondaryContainer = Color(0xFF5D3F3A),
    onSecondaryContainer = Color(0xFFFFDAD4),
    tertiary = Color(0xFFDDC48C),
    onTertiary = Color(0xFF3D2E04),
    tertiaryContainer = Color(0xFF564519),
    onTertiaryContainer = Color(0xFFFAE0A6),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1A1110),
    onBackground = Color(0xFFF1DFDB),
    surface = Color(0xFF1A1110),
    onSurface = Color(0xFFF1DFDB),
    surfaceVariant = Color(0xFF534340),
    onSurfaceVariant = Color(0xFFD8C2BE),
    inverseSurface = Color(0xFFF1DFDB),
    inverseOnSurface = Color(0xFF392E2C),
    outline = Color(0xFFA08C89),
    outlineVariant = Color(0xFF534340),
    scrim = Color(0xFF000000),
    surfaceDim = Color(0xFF1A1110),
    surfaceBright = Color(0xFF423735),
    surfaceContainerLowest = Color(0xFF140C0B),
    surfaceContainerLow = Color(0xFF231918),
    surfaceContainer = Color(0xFF271D1C),
    surfaceContainerHigh = Color(0xFF322826),
    surfaceContainerHighest = Color(0xFF3D3230),
)

// ── PURPLE ────────────────────────────────────────────────────────────────────

internal val PurpleLightColorScheme = lightColorScheme(
    primary = Color(0xFF7D4E7E),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD6FB),
    onPrimaryContainer = Color(0xFF320936),
    inversePrimary = Color(0xFFEDB4EB),
    secondary = Color(0xFF6C586A),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF5DBF1),
    onSecondaryContainer = Color(0xFF261626),
    tertiary = Color(0xFF825249),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDAD3),
    onTertiaryContainer = Color(0xFF33110B),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFF7FA),
    onBackground = Color(0xFF1F1A1F),
    surface = Color(0xFFFFF7FA),
    onSurface = Color(0xFF1F1A1F),
    surfaceVariant = Color(0xFFEDDEE8),
    onSurfaceVariant = Color(0xFF4D444C),
    inverseSurface = Color(0xFF352E34),
    inverseOnSurface = Color(0xFFF9EEF4),
    outline = Color(0xFF7F747C),
    outlineVariant = Color(0xFFD0C3CC),
    scrim = Color(0xFF000000),
    surfaceDim = Color(0xFFE2D7DE),
    surfaceBright = Color(0xFFFFF7FA),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFCF0F7),
    surfaceContainer = Color(0xFFF6EBF1),
    surfaceContainerHigh = Color(0xFFF1E5EC),
    surfaceContainerHighest = Color(0xFFEBDFE6),
)

internal val PurpleDarkColorScheme = darkColorScheme(
    primary = Color(0xFFEDB4EB),
    onPrimary = Color(0xFF4A204D),
    primaryContainer = Color(0xFF633664),
    onPrimaryContainer = Color(0xFFFFD6FB),
    inversePrimary = Color(0xFF7D4E7E),
    secondary = Color(0xFFD8BFD4),
    onSecondary = Color(0xFF3C2B3B),
    secondaryContainer = Color(0xFF534152),
    onSecondaryContainer = Color(0xFFF5DBF1),
    tertiary = Color(0xFFF6B8AC),
    onTertiary = Color(0xFF4C251E),
    tertiaryContainer = Color(0xFF673B33),
    onTertiaryContainer = Color(0xFFFFDAD3),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF171216),
    onBackground = Color(0xFFEBDFE6),
    surface = Color(0xFF171216),
    onSurface = Color(0xFFEBDFE6),
    surfaceVariant = Color(0xFF4D444C),
    onSurfaceVariant = Color(0xFFD0C3CC),
    inverseSurface = Color(0xFFEBDFE6),
    inverseOnSurface = Color(0xFF352E34),
    outline = Color(0xFF998D96),
    outlineVariant = Color(0xFF4D444C),
    scrim = Color(0xFF000000),
    surfaceDim = Color(0xFF171216),
    surfaceBright = Color(0xFF3E373C),
    surfaceContainerLowest = Color(0xFF120D11),
    surfaceContainerLow = Color(0xFF1F1A1F),
    surfaceContainer = Color(0xFF241E23),
    surfaceContainerHigh = Color(0xFF2E282D),
    surfaceContainerHighest = Color(0xFF393338),
)

// ── BLUE ──────────────────────────────────────────────────────────────────────

internal val BlueLightColorScheme = lightColorScheme(
    primary = Color(0xFF37618E),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD2E4FF),
    onPrimaryContainer = Color(0xFF001D36),
    inversePrimary = Color(0xFFA1CAFD),
    secondary = Color(0xFF535F70),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD7E3F8),
    onSecondaryContainer = Color(0xFF101C2B),
    tertiary = Color(0xFF6B5778),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF3DAFF),
    onTertiaryContainer = Color(0xFF251431),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF8F9FF),
    onBackground = Color(0xFF191C20),
    surface = Color(0xFFF8F9FF),
    onSurface = Color(0xFF191C20),
    surfaceVariant = Color(0xFFDFE2EB),
    onSurfaceVariant = Color(0xFF43474E),
    inverseSurface = Color(0xFF2E3135),
    inverseOnSurface = Color(0xFFEFF0F7),
    outline = Color(0xFF73777F),
    outlineVariant = Color(0xFFC3C6CF),
    scrim = Color(0xFF000000),
    surfaceDim = Color(0xFFD8DAE0),
    surfaceBright = Color(0xFFF8F9FF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF2F3FA),
    surfaceContainer = Color(0xFFECEEF4),
    surfaceContainerHigh = Color(0xFFE6E8EE),
    surfaceContainerHighest = Color(0xFFE1E2E8),
)

internal val BlueDarkColorScheme = darkColorScheme(
    primary = Color(0xFFA1CAFD),
    onPrimary = Color(0xFF003259),
    primaryContainer = Color(0xFF1A4975),
    onPrimaryContainer = Color(0xFFD2E4FF),
    inversePrimary = Color(0xFF37618E),
    secondary = Color(0xFFBBC7DB),
    onSecondary = Color(0xFF253140),
    secondaryContainer = Color(0xFF3C4858),
    onSecondaryContainer = Color(0xFFD7E3F8),
    tertiary = Color(0xFFD7BEE4),
    onTertiary = Color(0xFF3B2947),
    tertiaryContainer = Color(0xFF533F5F),
    onTertiaryContainer = Color(0xFFF3DAFF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF111418),
    onBackground = Color(0xFFE1E2E8),
    surface = Color(0xFF111418),
    onSurface = Color(0xFFE1E2E8),
    surfaceVariant = Color(0xFF43474E),
    onSurfaceVariant = Color(0xFFC3C6CF),
    inverseSurface = Color(0xFFE1E2E8),
    inverseOnSurface = Color(0xFF2E3135),
    outline = Color(0xFF8D9199),
    outlineVariant = Color(0xFF43474E),
    scrim = Color(0xFF000000),
    surfaceDim = Color(0xFF111418),
    surfaceBright = Color(0xFF36393E),
    surfaceContainerLowest = Color(0xFF0B0E13),
    surfaceContainerLow = Color(0xFF191C20),
    surfaceContainer = Color(0xFF1D2024),
    surfaceContainerHigh = Color(0xFF272A2F),
    surfaceContainerHighest = Color(0xFF32353A),
)

// ── GREEN ─────────────────────────────────────────────────────────────────────

internal val GreenLightColorScheme = lightColorScheme(
    primary = Color(0xFF126B56),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFA3F2D8),
    onPrimaryContainer = Color(0xFF002018),
    inversePrimary = Color(0xFF87D6BC),
    secondary = Color(0xFF4B635B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCEE9DD),
    onSecondaryContainer = Color(0xFF072019),
    tertiary = Color(0xFF416276),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFC4E7FF),
    onTertiaryContainer = Color(0xFF001E2C),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF5FBF6),
    onBackground = Color(0xFF171D1A),
    surface = Color(0xFFF5FBF6),
    onSurface = Color(0xFF171D1A),
    surfaceVariant = Color(0xFFDBE5DF),
    onSurfaceVariant = Color(0xFF3F4945),
    inverseSurface = Color(0xFF2B322F),
    inverseOnSurface = Color(0xFFECF2EE),
    outline = Color(0xFF6F7975),
    outlineVariant = Color(0xFFBFC9C3),
    scrim = Color(0xFF000000),
    surfaceDim = Color(0xFFD5DBD7),
    surfaceBright = Color(0xFFF5FBF6),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFEFF5F1),
    surfaceContainer = Color(0xFFE9EFEB),
    surfaceContainerHigh = Color(0xFFE3EAE5),
    surfaceContainerHighest = Color(0xFFDEE4E0),
)

internal val GreenDarkColorScheme = darkColorScheme(
    primary = Color(0xFF87D6BC),
    onPrimary = Color(0xFF00382B),
    primaryContainer = Color(0xFF005140),
    onPrimaryContainer = Color(0xFFA3F2D8),
    inversePrimary = Color(0xFF126B56),
    secondary = Color(0xFFB2CCC1),
    onSecondary = Color(0xFF1D352D),
    secondaryContainer = Color(0xFF344C43),
    onSecondaryContainer = Color(0xFFCEE9DD),
    tertiary = Color(0xFFA8CBE2),
    onTertiary = Color(0xFF0D3446),
    tertiaryContainer = Color(0xFF284B5E),
    onTertiaryContainer = Color(0xFFC4E7FF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0F1512),
    onBackground = Color(0xFFDEE4E0),
    surface = Color(0xFF0F1512),
    onSurface = Color(0xFFDEE4E0),
    surfaceVariant = Color(0xFF3F4945),
    onSurfaceVariant = Color(0xFFBFC9C3),
    inverseSurface = Color(0xFFDEE4E0),
    inverseOnSurface = Color(0xFF2B322F),
    outline = Color(0xFF89938E),
    outlineVariant = Color(0xFF3F4945),
    scrim = Color(0xFF000000),
    surfaceDim = Color(0xFF0F1512),
    surfaceBright = Color(0xFF343B38),
    surfaceContainerLowest = Color(0xFF090F0D),
    surfaceContainerLow = Color(0xFF171D1A),
    surfaceContainer = Color(0xFF1B211E),
    surfaceContainerHigh = Color(0xFF252B29),
    surfaceContainerHighest = Color(0xFF303633),
)

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Applies true-black (AMOLED) surface overrides to a dark color scheme.
 * Mirrors the night-mode `Theme.Kitsune.DayNight.*Black` XML overrides.
 */
internal fun ColorScheme.withAmoledSurfaces(): ColorScheme {
    // Shift the lighter containers down to fill the gap left by the true-black
    // background/surface, matching what the XML Black theme does.
    val origLowest = surfaceContainerLowest
    val origLow = surfaceContainerLow
    val origContainer = surfaceContainer
    return copy(
        background = Color.Black,
        surface = Color.Black,
        surfaceContainerLowest = Color.Black,
        surfaceContainerLow = Color.Black,
        surfaceContainer = origLowest,
        surfaceContainerHigh = origLow,
        surfaceContainerHighest = origContainer,
    )
}

/** Returns the Kotlin-defined [ColorScheme] for the given [variant] and brightness. */
internal fun colorSchemeForVariant(variant: AppTheme, dark: Boolean): ColorScheme = when (variant) {
    AppTheme.DEFAULT -> if (dark) DefaultDarkColorScheme else DefaultLightColorScheme
    AppTheme.PURPLE -> if (dark) PurpleDarkColorScheme else PurpleLightColorScheme
    AppTheme.BLUE -> if (dark) BlueDarkColorScheme else BlueLightColorScheme
    AppTheme.GREEN -> if (dark) GreenDarkColorScheme else GreenLightColorScheme
}
