name: Build app

on:
  workflow_dispatch:
    inputs:
      buildVariant:
        description: 'App build variant'
        required: false
        default: 'release'
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set gradle build task
        run: |
          if [ -z "${{ github.event.inputs.buildVariant }}" ]; then
            echo "build_task='assembleRelease'" >> "$GITHUB_ENV"
          else
            echo "build_task=${{ github.event.inputs.buildVariant }}" >> "$GITHUB_ENV"
          fi
      - name: Build release with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "$build_task"
      - name: Upload release apk
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
