name: Build app

on: [ workflow_dispatch, workflow_call ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install build-tools 34.0.0
        run: echo y | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0" "platforms;android-34"
      - name: Uninstall build-tools 35.0.0
        run: echo y | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --uninstall "build-tools;35.0.0"
      - name: List installed build-tools
        run: /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --list_installed
      - name: List android SDK files
        run: ls -Rl /usr/local/lib/android
      - name: Build release with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease
      - name: Upload release apk
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
